# Generated by Django 3.1 on 2020-08-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('localizacao', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('pontos', '0002_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTuristicos',
            new_name='PontoTuristico',
        ),
    ]
