# Generated by Django 3.1 on 2020-08-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_auto_20200821_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
